# Railway Deployment Configuration
# This file tells Railway how to deploy your backend

[build]
  command = "npm run build"

[start]
  command = "npm start"

[healthcheck]
  path = "/api/health"

[environments.production]
  PORT = 5000
  NODE_ENV = "production"