# Render deployment configuration
# Place this file in your backend directory

services:
  - type: web
    name: ecommerce-backend
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false  # You'll set this manually in Render dashboard