name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Clear npm cache
      run: npm cache clean --force
      
    - name: Install frontend dependencies
      run: npm install
      
    - name: Build frontend
      run: npm run build
      env:
        # Use GitHub secret for production API URL
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL || 'https://your-backend-service.onrender.com/api' }}
        VITE_APP_ENV: production
        # Ensure compatibility
        NODE_ENV: production
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist